-- Categories Table
CREATE TABLE Categories (
    CATEGORY_ID INT IDENTITY(1,1) PRIMARY KEY,
    CATEGORY_NAME NVARCHAR(100) NOT NULL,
    PARENT_CATEGORY_ID INT NULL,
    DISPLAY_ORDER INT NOT NULL DEFAULT 0
);

-- Add index on CATEGORY_NAME for faster lookups
CREATE INDEX IDX_CATEGORY_NAME ON Categories (CATEGORY_NAME);

-- Add index on PARENT_CATEGORY_ID for faster parent-child lookups
CREATE INDEX IDX_PARENT_CATEGORY_ID ON Categories (PARENT_CATEGORY_ID);

-- Sample data for Categories table
INSERT INTO Categories (CATEGORY_NAME, PARENT_CATEGORY_ID, DISPLAY_ORDER)
VALUES ('T-Shirts', NULL, 1);

INSERT INTO Categories (CATEGORY_NAME, PARENT_CATEGORY_ID, DISPLAY_ORDER)
VALUES ('Polos', NULL, 2);

INSERT INTO Categories (CATEGORY_NAME, PARENT_CATEGORY_ID, DISPLAY_ORDER)
VALUES ('Outerwear', NULL, 3);

INSERT INTO Categories (CATEGORY_NAME, PARENT_CATEGORY_ID, DISPLAY_ORDER)
VALUES ('Pants', NULL, 4);

INSERT INTO Categories (CATEGORY_NAME, PARENT_CATEGORY_ID, DISPLAY_ORDER)
VALUES ('Shorts', NULL, 5);

INSERT INTO Categories (CATEGORY_NAME, PARENT_CATEGORY_ID, DISPLAY_ORDER)
VALUES ('Workwear', NULL, 6);

INSERT INTO Categories (CATEGORY_NAME, PARENT_CATEGORY_ID, DISPLAY_ORDER)
VALUES ('Activewear', NULL, 7);

INSERT INTO Categories (CATEGORY_NAME, PARENT_CATEGORY_ID, DISPLAY_ORDER)
VALUES ('Accessories', NULL, 8);

-- Add some subcategories
INSERT INTO Categories (CATEGORY_NAME, PARENT_CATEGORY_ID, DISPLAY_ORDER)
VALUES ('Crew Neck T-Shirts', 1, 1);

INSERT INTO Categories (CATEGORY_NAME, PARENT_CATEGORY_ID, DISPLAY_ORDER)
VALUES ('V-Neck T-Shirts', 1, 2);

INSERT INTO Categories (CATEGORY_NAME, PARENT_CATEGORY_ID, DISPLAY_ORDER)
VALUES ('Long Sleeve T-Shirts', 1, 3);

INSERT INTO Categories (CATEGORY_NAME, PARENT_CATEGORY_ID, DISPLAY_ORDER)
VALUES ('Sport Polos', 2, 1);

INSERT INTO Categories (CATEGORY_NAME, PARENT_CATEGORY_ID, DISPLAY_ORDER)
VALUES ('Dress Polos', 2, 2);

INSERT INTO Categories (CATEGORY_NAME, PARENT_CATEGORY_ID, DISPLAY_ORDER)
VALUES ('Jackets', 3, 1);

INSERT INTO Categories (CATEGORY_NAME, PARENT_CATEGORY_ID, DISPLAY_ORDER)
VALUES ('Fleece', 3, 2);

INSERT INTO Categories (CATEGORY_NAME, PARENT_CATEGORY_ID, DISPLAY_ORDER)
VALUES ('Vests', 3, 3);