-- Color Mapping Table
CREATE TABLE ColorMapping (
    MAPPING_ID INT IDENTITY(1,1) PRIMARY KEY,
    API_COLOR_NAME NVARCHAR(100) NOT NULL,
    DISPLAY_COLOR_NAME NVARCHAR(100) NOT NULL,
    LAST_UPDATED DATETIME NOT NULL DEFAULT GETDATE()
);

-- Add unique constraint on API_COLOR_NAME to prevent duplicates
CREATE UNIQUE INDEX IDX_API_COLOR_NAME ON ColorMapping (API_COLOR_NAME);

-- Sample data for ColorMapping table
INSERT INTO ColorMapping (API_COLOR_NAME, DISPLAY_COLOR_NAME, LAST_UPDATED)
VALUES ('BLK', 'Black', GETDATE());

INSERT INTO ColorMapping (API_COLOR_NAME, DISPLAY_COLOR_NAME, LAST_UPDATED)
VALUES ('WHT', 'White', GETDATE());

INSERT INTO ColorMapping (API_COLOR_NAME, DISPLAY_COLOR_NAME, LAST_UPDATED)
VALUES ('NVY', 'Navy', GETDATE());

INSERT INTO ColorMapping (API_COLOR_NAME, DISPLAY_COLOR_NAME, LAST_UPDATED)
VALUES ('RED', 'Red', GETDATE());

INSERT INTO ColorMapping (API_COLOR_NAME, DISPLAY_COLOR_NAME, LAST_UPDATED)
VALUES ('ROY', 'Royal', GETDATE());

INSERT INTO ColorMapping (API_COLOR_NAME, DISPLAY_COLOR_NAME, LAST_UPDATED)
VALUES ('ATHL HTH', 'Athletic Heather', GETDATE());

INSERT INTO ColorMapping (API_COLOR_NAME, DISPLAY_COLOR_NAME, LAST_UPDATED)
VALUES ('ATHHTHR', 'Athletic Heather', GETDATE());

INSERT INTO ColorMapping (API_COLOR_NAME, DISPLAY_COLOR_NAME, LAST_UPDATED)
VALUES ('DKGRN', 'Dark Green', GETDATE());

INSERT INTO ColorMapping (API_COLOR_NAME, DISPLAY_COLOR_NAME, LAST_UPDATED)
VALUES ('DKGRY', 'Dark Grey', GETDATE());

INSERT INTO ColorMapping (API_COLOR_NAME, DISPLAY_COLOR_NAME, LAST_UPDATED)
VALUES ('LTGRY', 'Light Grey', GETDATE());

INSERT INTO ColorMapping (API_COLOR_NAME, DISPLAY_COLOR_NAME, LAST_UPDATED)
VALUES ('MAROON', 'Maroon', GETDATE());

INSERT INTO ColorMapping (API_COLOR_NAME, DISPLAY_COLOR_NAME, LAST_UPDATED)
VALUES ('PURPLE', 'Purple', GETDATE());

INSERT INTO ColorMapping (API_COLOR_NAME, DISPLAY_COLOR_NAME, LAST_UPDATED)
VALUES ('SANGRIA', 'Sangria', GETDATE());

INSERT INTO ColorMapping (API_COLOR_NAME, DISPLAY_COLOR_NAME, LAST_UPDATED)
VALUES ('TRBLUE', 'True Blue', GETDATE());

INSERT INTO ColorMapping (API_COLOR_NAME, DISPLAY_COLOR_NAME, LAST_UPDATED)
VALUES ('TRROYAL', 'True Royal', GETDATE());

INSERT INTO ColorMapping (API_COLOR_NAME, DISPLAY_COLOR_NAME, LAST_UPDATED)
VALUES ('WASABE', 'Wasabe', GETDATE());

-- Color codes with slashes
INSERT INTO ColorMapping (API_COLOR_NAME, DISPLAY_COLOR_NAME, LAST_UPDATED)
VALUES ('BLK/WHT', 'Black/White', GETDATE());

INSERT INTO ColorMapping (API_COLOR_NAME, DISPLAY_COLOR_NAME, LAST_UPDATED)
VALUES ('NVY/WHT', 'Navy/White', GETDATE());

INSERT INTO ColorMapping (API_COLOR_NAME, DISPLAY_COLOR_NAME, LAST_UPDATED)
VALUES ('RED/WHT', 'Red/White', GETDATE());

INSERT INTO ColorMapping (API_COLOR_NAME, DISPLAY_COLOR_NAME, LAST_UPDATED)
VALUES ('ROY/WHT', 'Royal/White', GETDATE());

-- Color codes with hyphens
INSERT INTO ColorMapping (API_COLOR_NAME, DISPLAY_COLOR_NAME, LAST_UPDATED)
VALUES ('BLK-WHT', 'Black/White', GETDATE());

INSERT INTO ColorMapping (API_COLOR_NAME, DISPLAY_COLOR_NAME, LAST_UPDATED)
VALUES ('NVY-WHT', 'Navy/White', GETDATE());

INSERT INTO ColorMapping (API_COLOR_NAME, DISPLAY_COLOR_NAME, LAST_UPDATED)
VALUES ('RED-WHT', 'Red/White', GETDATE());

INSERT INTO ColorMapping (API_COLOR_NAME, DISPLAY_COLOR_NAME, LAST_UPDATED)
VALUES ('ROY-WHT', 'Royal/White', GETDATE());