-- Inventory Table
CREATE TABLE Inventory (
    INVENTORY_ID INT IDENTITY(1,1) PRIMARY KEY,
    STYLE NVARCHAR(50) NOT NULL,
    COLOR_NAME NVARCHAR(100) NOT NULL,
    DISPLAY_COLOR NVARCHAR(100) NOT NULL,
    SIZE NVARCHAR(20) NOT NULL,
    WAREHOUSE_ID NVARCHAR(20) NOT NULL,
    QUANTITY INT NOT NULL DEFAULT 0,
    LAST_UPDATED DATETIME NOT NULL DEFAULT GETDATE()
);

-- Add indexes for faster lookups
CREATE INDEX IDX_STYLE_COLOR_SIZE ON Inventory (STYLE, COLOR_NAME, SIZE);
CREATE INDEX IDX_WAREHOUSE_ID ON Inventory (WAREHOUSE_ID);
CREATE INDEX IDX_DISPLAY_COLOR ON Inventory (DISPLAY_COLOR);

-- Sample data for Inventory table
-- PC61 White S
INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('PC61', 'WHT', 'White', 'S', '1', 120, GETDATE());

INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('PC61', 'WHT', 'White', 'S', '2', 85, GETDATE());

INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('PC61', 'WHT', 'White', 'S', '3', 65, GETDATE());

-- PC61 White M
INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('PC61', 'WHT', 'White', 'M', '1', 150, GETDATE());

INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('PC61', 'WHT', 'White', 'M', '2', 110, GETDATE());

INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('PC61', 'WHT', 'White', 'M', '3', 90, GETDATE());

-- PC61 White L
INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('PC61', 'WHT', 'White', 'L', '1', 180, GETDATE());

INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('PC61', 'WHT', 'White', 'L', '2', 135, GETDATE());

INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('PC61', 'WHT', 'White', 'L', '3', 105, GETDATE());

-- PC61 White XL
INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('PC61', 'WHT', 'White', 'XL', '1', 160, GETDATE());

INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('PC61', 'WHT', 'White', 'XL', '2', 120, GETDATE());

INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('PC61', 'WHT', 'White', 'XL', '3', 95, GETDATE());

-- PC61 White 2XL
INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('PC61', 'WHT', 'White', '2XL', '1', 100, GETDATE());

INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('PC61', 'WHT', 'White', '2XL', '2', 75, GETDATE());

INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('PC61', 'WHT', 'White', '2XL', '3', 60, GETDATE());

-- PC61 Black S
INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('PC61', 'BLK', 'Black', 'S', '1', 110, GETDATE());

INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('PC61', 'BLK', 'Black', 'S', '2', 80, GETDATE());

INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('PC61', 'BLK', 'Black', 'S', '3', 60, GETDATE());

-- PC61 Black M
INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('PC61', 'BLK', 'Black', 'M', '1', 140, GETDATE());

INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('PC61', 'BLK', 'Black', 'M', '2', 105, GETDATE());

INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('PC61', 'BLK', 'Black', 'M', '3', 85, GETDATE());

-- K500 Red M
INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('K500', 'RED', 'Red', 'M', '1', 75, GETDATE());

INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('K500', 'RED', 'Red', 'M', '2', 60, GETDATE());

INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('K500', 'RED', 'Red', 'M', '3', 45, GETDATE());

-- K500 Red L
INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('K500', 'RED', 'Red', 'L', '1', 90, GETDATE());

INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('K500', 'RED', 'Red', 'L', '2', 70, GETDATE());

INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('K500', 'RED', 'Red', 'L', '3', 55, GETDATE());

-- J317 Black M
INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('J317', 'BLK', 'Black', 'M', '1', 40, GETDATE());

INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('J317', 'BLK', 'Black', 'M', '2', 30, GETDATE());

INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('J317', 'BLK', 'Black', 'M', '3', 25, GETDATE());

-- J317 Black L
INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('J317', 'BLK', 'Black', 'L', '1', 50, GETDATE());

INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('J317', 'BLK', 'Black', 'L', '2', 40, GETDATE());

INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('J317', 'BLK', 'Black', 'L', '3', 30, GETDATE());

-- J317 Black XL
INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('J317', 'BLK', 'Black', 'XL', '1', 45, GETDATE());

INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('J317', 'BLK', 'Black', 'XL', '2', 35, GETDATE());

INSERT INTO Inventory (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, WAREHOUSE_ID, QUANTITY, LAST_UPDATED)
VALUES ('J317', 'BLK', 'Black', 'XL', '3', 25, GETDATE());