-- Pricing Table
CREATE TABLE Pricing (
    PRICING_ID INT IDENTITY(1,1) PRIMARY KEY,
    STYLE NVARCHAR(50) NOT NULL,
    COLOR_NAME NVARCHAR(100) NOT NULL,
    DISPLAY_COLOR NVARCHAR(100) NOT NULL,
    SIZE NVARCHAR(20) NOT NULL,
    PIECE_PRICE DECIMAL(10, 2) NOT NULL DEFAULT 0,
    CASE_PRICE DECIMAL(10, 2) NOT NULL DEFAULT 0,
    PROGRAM_PRICE DECIMAL(10, 2) NOT NULL DEFAULT 0,
    LAST_UPDATED DATETIME NOT NULL DEFAULT GETDATE()
);

-- Add indexes for faster lookups
CREATE INDEX IDX_PRICING_STYLE_COLOR_SIZE ON Pricing (STYLE, COLOR_NAME, SIZE);
CREATE INDEX IDX_PRICING_DISPLAY_COLOR ON Pricing (DISPLAY_COLOR);

-- Sample data for Pricing table
-- PC61 White S
INSERT INTO Pricing (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, PIECE_PRICE, CASE_PRICE, PROGRAM_PRICE, LAST_UPDATED)
VALUES ('PC61', 'WHT', 'White', 'S', 4.99, 359.28, 4.49, GETDATE());

-- PC61 White M
INSERT INTO Pricing (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, PIECE_PRICE, CASE_PRICE, PROGRAM_PRICE, LAST_UPDATED)
VALUES ('PC61', 'WHT', 'White', 'M', 4.99, 359.28, 4.49, GETDATE());

-- PC61 White L
INSERT INTO Pricing (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, PIECE_PRICE, CASE_PRICE, PROGRAM_PRICE, LAST_UPDATED)
VALUES ('PC61', 'WHT', 'White', 'L', 4.99, 359.28, 4.49, GETDATE());

-- PC61 White XL
INSERT INTO Pricing (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, PIECE_PRICE, CASE_PRICE, PROGRAM_PRICE, LAST_UPDATED)
VALUES ('PC61', 'WHT', 'White', 'XL', 4.99, 359.28, 4.49, GETDATE());

-- PC61 White 2XL
INSERT INTO Pricing (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, PIECE_PRICE, CASE_PRICE, PROGRAM_PRICE, LAST_UPDATED)
VALUES ('PC61', 'WHT', 'White', '2XL', 6.99, 251.64, 6.29, GETDATE());

-- PC61 Black S
INSERT INTO Pricing (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, PIECE_PRICE, CASE_PRICE, PROGRAM_PRICE, LAST_UPDATED)
VALUES ('PC61', 'BLK', 'Black', 'S', 4.99, 359.28, 4.49, GETDATE());

-- PC61 Black M
INSERT INTO Pricing (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, PIECE_PRICE, CASE_PRICE, PROGRAM_PRICE, LAST_UPDATED)
VALUES ('PC61', 'BLK', 'Black', 'M', 4.99, 359.28, 4.49, GETDATE());

-- PC61 Black L
INSERT INTO Pricing (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, PIECE_PRICE, CASE_PRICE, PROGRAM_PRICE, LAST_UPDATED)
VALUES ('PC61', 'BLK', 'Black', 'L', 4.99, 359.28, 4.49, GETDATE());

-- PC61 Black XL
INSERT INTO Pricing (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, PIECE_PRICE, CASE_PRICE, PROGRAM_PRICE, LAST_UPDATED)
VALUES ('PC61', 'BLK', 'Black', 'XL', 4.99, 359.28, 4.49, GETDATE());

-- PC61 Black 2XL
INSERT INTO Pricing (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, PIECE_PRICE, CASE_PRICE, PROGRAM_PRICE, LAST_UPDATED)
VALUES ('PC61', 'BLK', 'Black', '2XL', 6.99, 251.64, 6.29, GETDATE());

-- K500 Red M
INSERT INTO Pricing (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, PIECE_PRICE, CASE_PRICE, PROGRAM_PRICE, LAST_UPDATED)
VALUES ('K500', 'RED', 'Red', 'M', 14.99, 2158.56, 13.49, GETDATE());

-- K500 Red L
INSERT INTO Pricing (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, PIECE_PRICE, CASE_PRICE, PROGRAM_PRICE, LAST_UPDATED)
VALUES ('K500', 'RED', 'Red', 'L', 14.99, 2158.56, 13.49, GETDATE());

-- J317 Black M
INSERT INTO Pricing (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, PIECE_PRICE, CASE_PRICE, PROGRAM_PRICE, LAST_UPDATED)
VALUES ('J317', 'BLK', 'Black', 'M', 39.99, 5758.56, 35.99, GETDATE());

-- J317 Black L
INSERT INTO Pricing (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, PIECE_PRICE, CASE_PRICE, PROGRAM_PRICE, LAST_UPDATED)
VALUES ('J317', 'BLK', 'Black', 'L', 39.99, 5758.56, 35.99, GETDATE());

-- J317 Black XL
INSERT INTO Pricing (STYLE, COLOR_NAME, DISPLAY_COLOR, SIZE, PIECE_PRICE, CASE_PRICE, PROGRAM_PRICE, LAST_UPDATED)
VALUES ('J317', 'BLK', 'Black', 'XL', 39.99, 5758.56, 35.99, GETDATE());